services:
  app:
      build: .
      container_name: tukki
      restart: unless-stopped
      expose:
        - 5000
      environment:
        - FLASK_ENV=production
        - PYTHONPATH=/app
      volumes:
        - ./logs:/app/logs
      networks:
        - api-network

networks:
  api-network:
    driver: bridge